model:
  gnn_type: "GPS"
  num_heads: 4  # only applicable for GAT
  edge_encoder_hidden_dim: 128
  node_encoder_hidden_dim: 128
  out_dim: 2
  gnn_layers: 5
  noise_std: 0.01
  dropout_prob: 0.3

training:
  lr: 0.0001
  batch_size: 32
  epochs: 300
  test_split: 0.2  # percentage data in the test split
  val_split: 0.1  # percentage of data in the validation split
  gt_edges: True  # whether to train with ground truth edges or not
  validate_with_rollout: False
  downsample_timestep: 256  # 1 indicates no downsampling
  pred_pos: False
